### ISSUE TITLE
truffle unbox not working

### ISSUE THREAD

**Issue by SassanoM** [blockchangers/eth-truffle-vue#2]
Hello,

truffle unbox is not working for your box, the following command throws an error:

`truffle unbox blockchangers/eth-truffle-vue`

I think (maybe) this is because the repo is missing an "truffle.js" file.

Error below:

`Error: Truffle Box at URL https://github.com/blockchangers/eth-truffle-vue doesn't exist. If you believe this is an error, please contact Truffle support.
    at Request._callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-box/lib/utils/unbox.js:50:1)
    at Request.self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:186:1)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1163:1)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1085:1)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)`

**Comment by RobertoSnap** [comment]
Thank you for reporting the issue. 

I have added a simple truffle.js in the root folder to circument this problem. 

@DiscRiskandBisque , is it possible to remove the requirement to have a truffle.js file in root folder?
